---
title: "Home"
---

## Recent Activities

- 2024/12/17-12/19 Participated in [7th Intensive Lectures by Quantum Gravity Gatherings](https://qgg.riken.jp/session7.htm) held at [RIKEN iTHEMS](https://ithems.riken.jp/en).
- 2024/12/10 Presented at the poster session of [New Trends in Condensed Matter Theory 2024 at ISSP UTokyo](https://oka.issp.u-tokyo.ac.jp/ntcmt2024/ntcmt2024.html).
    - The poster can be found [here](Phys_resources/slides/new_trends_in_condmat_th_poster.pdf).
- 2024/12/06 Made a presentation at [the colloquium on applied physics I](https://www.ap.t.u-tokyo.ac.jp/lecture/journal_club02/).
    - The presentation material is kept private because many parts of the presentation relied on specific references. I apologize to those who were looking forward to it.
- 2024/12/06 Made a presentation at the joint seminar of master students (theoretical) in the dept of applied phys.
    - The presentation slides can be found [here](Phys_resources/slides/joint_seminar_threefoldway.pdf).
- 2024/10/16 Research with [Ken Mochizuki](https://damp-saiki-9142.fakefur.jp/english.html) and [Zongping Gong](https://sites.google.com/site/zongpinggong/) has been uploaded to arXiv: *[Threefold Way for Typical Entanglement](https://arxiv.org/abs/2410.11309v1)*
- 2024/09/16-09/19 Participated in [The Physical Society of Japan 2024 Annual Meating](https://www.jps.or.jp/activities/meetings/annual/annual-index.php) held at Hokkaido university. 
    - The presentation slides (in Japanese) can be found [here](Phys_resources/slides/jps79th_threefoldway.pdf).
- 2024/08/12-08/16 Participated in [Symmetries 2024](https://sites.google.com/view/symmetries2024/home) held at the university of Oxford.
- 2024/04/01 Joined [Gong group](https://sites.google.com/g.ecc.u-tokyo.ac.jp/gonggroup/), dept. of appl. phys., graduate school of eng., the Univ. of Tokyo.

<!-- ## Upcoming Events to Participate in

- 2024/12/25-12/27 [研究会「複素化による量子系に関する研究の発展」](https://kouji-kashiwa.github.io/workshop_complexification/) held at Saga university
- 2025/02/17-02/19 [FoPM Symposium](https://indico.ipmu.jp/event/420/overview) held at the university of Tokyo
- 2025/03/03-03/07 [Enumerative geometry, representation theory, and physics](https://indico.ipmu.jp/event/427/) held at Kavli IPMU, the University of Tokyo
- 2025/03/10-03/14 [Kyushu IAS-iTHEMS conference: Non-perturbative methods in QFT](https://indico2.riken.jp/event/5013/) held at Kyushu University Institute for Advanced Study -->