---
title: "Physics"
---

This page summarizes my research activities in physics.

# Research Works

Please click the title (the triangle mark) to view the basic information of the paper (related oral and poster presentations or supporting materials).


::: {.callout-note style=minimum icon=false collapse="true"}
## *Entanglement Spectrum Resolved by Loop Symmetries*
**Haruki Yagi** and Zongping Gong

- [arXiv:2510.18350](https://arxiv.org/abs/2510.18350)

<details><summary>Abstract</summary>
- A rigorous analysis is presented for the entanglement spectrum of quantum many-body states possessing a higher-form group-representation symmetry generated by topological Wilson loops, which is generally non-invertible. A general framework based on elementary algebraic topology and category theory is developed to determine the block structure of reduced density matrices for arbitrary bipartite manifolds on which the states are defined. Within this framework, we scrutinize the impact of topology on the entanglement structure for low-dimensional manifolds, including especially the torus, the Klein bottle, and lens spaces. By further incorporating gauge invariance, we refine our framework to determine the entanglement structure for topological gauge theories in arbitrary dimensions. In particular, in two dimensions, it is shown for the Kitaev quantum double model that not only the topological entanglement entropy can be reproduced, but also the Li-Haldane conjecture concerning the full entanglement spectrum holds exactly.
</details>

<details><summary>Supporting materials</summary>
- Coming soon!
</details>

:::


::: {.callout-note style=minimum icon=false collapse="true"}
## *Threefold Way for Typical Entanglement*
**Haruki Yagi**, Ken Mochizuki, and Zongping Gong

- [arXiv:2410.11309](https://arxiv.org/abs/2410.11309)
- [PhysRevLett.134.150401](https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.134.150401)

<details><summary>Abstract</summary>
- A typical quantum state with no symmetry can be realized by letting a random unitary act on a fixed state, and the subsystem entanglement spectrum follows the Laguerre unitary ensemble (LUE). For integer-spin time reversal symmetry, we have an analogous scenario where we prepare a time-reversal symmetric state and let random orthogonal matrices act on it, leading to the Laguerre orthogonal ensemble (LOE). However, for half-integer-spin time reversal symmetry, a straightforward analogue leading to the Laguerre symplectic ensemble (LSE) is no longer valid due to that time reversal symmetric state is forbidden by the Kramers' theorem. We devise a system in which the global time reversal operator is fractionalized on the subsystems, and show that LSE arises in the system. Extending this idea, we incorporate general symmetry fractionalization into the system, and show that the statistics of the entanglement spectrum is decomposed into a direct sum of LOE, LUE, and/or LSE. Here, various degeneracies in the entanglement spectrum may appear, depending on the non-Abelian nature of the symmetry group and the cohomology class of the non-trivial projective representation on the subsystem. Our work establishes the entanglement counterpart of the Dyson's threefold way for Hamiltonians with symmetries.
</details>

<details><summary>Supporting materials</summary>

- [Slides (English)](Phys_resources/slides/threefold_way_for_typical_entanglement_slides_en.pdf)
- [スライド (日本語)](Phys_resources/slides/threefold_way_for_typical_entanglement_slides_jp.pdf)
- [Poster (English)](Phys_resources/slides/threefold_way_for_typical_entanglement_poster_en.pdf)
</details>

:::

# Others

::: {.callout-tip style=minimum icon=false collapse="true"}
## CFT Camp 2026

Following last year, I will hold the CFT Camp 2026. 
Those wishing to participate should read [this PDF (in Japanese)](Phys_resources/others/cft_camp_about_2026.pdf).

:::

::: {.callout-tip style=minimum icon=false collapse="true"}
## CFT Camp 2025

To study conformal field theory (CFT) with friends, I organized and held CFT Camp at the University of Tokyo's Yamanaka Dormitory over a three-day period from April 3 to April 6, 2025. For details, please refer to [this PDF (in Japanese)](Phys_resources/others/cft_report_pub.pdf).

:::