---
title: "Derivation of the instanton solution by the path integral formalism"

---

In this post, I will derive the instanton solution by making use of the path integral formalism.

# The Euclidean path integral formulation

Assume Lagrangian $L$ is a function of the coordinates $q_i$ and velocities $\dot{q}_i$ of the system.

$$L=\frac{1}{2}m\dot{q}^2-V(q)$$

The action is defined as below:

$$S=\int_{t_i}^{t_f}Ldt$$

The path integral is defined below:

$$G(q_i,q_f;t)\equiv\int_{q_i}^{q_f} Dq\; e^{iS/\hbar }\quad \left(=\langle q_f|e^{-iHt/\hbar}|q_i\rangle\right)$$

where $Dq$ is the path integral measure.

For ease of calculation, we introduce the Euclidean time $t\rightarrow-i\tau$ and the Euclidean path integral is defined as below:

$$G_E(q_i,q_f;\tau)\equiv\int_{q(\tau_i)=q_i}^{q(\tau_f)=q_f} Dq\; e^{-S_E/\hbar }\quad \left(=\langle q_f|e^{-\tau H/\hbar}|q_i\rangle\right)$$

where $S_E$ is the Euclidean action defined below:

$$S_E=\int_{\tau_i}^{\tau_f}\left(\frac{1}{2}m\dot{q}^2+V(q)\right) d\tau$$

Note that the dot means the derivative of the Euclidean time $\tau$. Because of the change in the coefficient of the time, the sign of the kinetic term is changed.

# The instanton gas

Consider the double-well potential (for the real time), such as the following:

$$V(q)=V_0\left(-\frac{1}{2}a^2q^2+\frac{1}{4}q^4\right).$$

This potential has two minima at $q=\pm a$ and one (local) maxima at $q=0$.

By executing the Wick rotation, we got a "Hamiltonian-like" Lagrangian, whose sign of potential term is changed. Therefore, it is effective to reckon motion over the inverted potential: $V\to-V$. Under this inversion, the potential has two maxima at $q=\pm a$ and one (local) minimum at $q=0$. Now we can find a classical solution that connects the two potential maxima **in the imaginary time**. 

The classical solution of the Euclidean equation of motion that connects the two potential-maxima is called an **instanton solution**$(-a\to a)$ while a solution traversing the same path but in the opposite direction is called an **anti-instanton solution**$(a\to -a)$.

To proceed, we must first compute the classical action associated with a single-instanton solution.
Here, the Lagrangian is given by

$$L=\frac{1}{2}m\dot{q}^2+V(q)$$

By applying the Euler-Lagrange equation, we get the equation of motion:

$$m\ddot{q_\mathrm{cl}}=\partial_q V(q_\mathrm{cl})$$

Multiplying the equation by $\dot{q}$ and integrating over the imaginary time $\tau$, we get the classical action:

$$\frac{m\dot{q}_\mathrm{cl}^2}{2}=V(q_\mathrm{cl})+\mathrm{const.}$$

To determine the constant, apply the condition: if $q_\mathrm{cl}=\pm a,\;V(q_\mathrm{cl})=0$

$$\frac{m\dot{q}_\mathrm{cl}^2}{2}=V(q)$$

With this result, we obtained the classical action of the instanton solution:


$$
\begin{aligned}
S_\mathrm{inst}&=\int_{0}^{\tau}\left(\frac{1}{2}m\dot{q}_\mathrm{cl}^2+V(q_\mathrm{cl})\right) d\tau\\
&=\int_{0}^{\tau}m\dot{q}_\mathrm{cl}^2 d\tau\\
&=\int_{0}^{\tau}m\dot{q}_\mathrm{cl} \frac{d q_\mathrm{cl}}{d\tau}d\tau\\
&=\int_{-a}^{a}m\dot{q}_\mathrm{cl} d q_\mathrm{cl}\\
&=\int_{-a}^{a}\sqrt{2mV(q_\mathrm{cl})} d q_\mathrm{cl}\\
\end{aligned}
$$

Notice that $S_\mathrm{inst}$ is determined solely by the potential $V(q)$. 

Here, we assume $V''(\pm a)=m\omega^2$, namely, $V(q)\simeq \frac{1}{2}m\left(q\mp a\right)^2$.
Substituting this for the following equation and differentiating for $\tau$,
$$
\begin{aligned}
\frac{m\dot{q}^2}{2}&=V(q)\\
\frac{m\dot{q}^2}{2}&=\frac{1}{2}m\omega^2\left(q\mp a\right)^2\\
\ddot{q}&=\omega^2\left(q\mp a\right)\\
(d_\tau^2-\omega^2)\left(q\mp a\right)&=0\\
q\mp a&=Ae^{\omega\tau}+Be^{-\omega\tau}\\
\end{aligned}
$$
where $A$ and $B$ are constants.
We don't care about divergent terms, so we set $A=0$.
For large $\tau$, we have $q\sim \pm a + Be^{-\omega\tau}$. Thus, the time spread of instantons is determined by the oscillator frequency of the local potential minima (the maxima of the inversion potential) and can be considered short if the tunneling occurs on a much larger time scale than that.

The fact that the instanton configuration is limited to a narrow time interval is important in that there are approximate solutions to the stationary equations involving further anti-instanton and instanton pairs. According to the general idea of the saddle-point method, the path integral is obtained by summing over all solutions of the saddle-point equation, that is, over all instanton configurations. The summation over multiple instanton configurations called **instanton gas**, is greatly simplified by the fact that the transition times of individual instantons are short and the number of instantons that can be accommodated in a finite time interval is dilute without being too large.

# Practical calculation

In practice, multi-instanton configuations imply a transition amplitude:
$$G(a,\pm a;\tau)\simeq \sum_{n\mathrm{\;even/odd}} K^n\int_0^\tau d\tau_1 \int_0^{\tau_1} d\tau_2 \cdots \int_0^{\tau_{n-1}} d\tau_{n} A_n\left(\tau_1,\cdots,\tau_n\right)$$
where $A_n$ denotes the amplitude of the $n$-instanton configuration and $K$ is a constant to absorb the dimention $\mathrm{\left[time\right]}^n$. In order to connect $a$ with $\pm a$, the number of instantons must be even/odd. 

In general, amplitude $A_n$ can be decomposed into a product of two factors: the classical part $A_{n,\mathrm{cl}}$ and the quantum part $A_{n,\mathrm{q}}$.
The classical contribution $A_{n,\mathrm{cl}}$ is given by the action of the instanton configuration.
On the other hand, the quantum contribution $A_{n,\mathrm{q}}$ is given by quadratic fluctuations around the classical solution.

Because each instanton has the same classical action, the classical contribution is given by the following:
$$A_{n,\mathrm{cl}}\left(\tau_1,\cdots,\tau_n\right)=e^{-nS_\mathrm{inst}/\hbar }$$
where $S_\mathrm{inst}$ is the classical action of a single instanton.

There are some clues to derive the quantum contribution $A_{n,\mathrm{q}}$, revoke the fact that quantum fluctuations around a classical configuration which stays for a (real) time $t$ at the bottom of the well result in a factor $\sqrt{1/\sin{\omega t}}$ (the remaining constants are absorbed into the constant $K$). Simply rotating to the imaginary time $t\to -i\tau$, we get the factor $\sqrt{1/\sinh{\omega\tau}}$. Assuming the dillute instanton gas, $\tau$ is so large that this approximation is allowed (It takes the particle much longer to tunnel through a high barrier than to oscillate in either of the wells of the real potential.):

$$\sqrt{\frac{1}{\sinh{\omega\tau}}}\sim e^{-\omega \tau/2}$$

Thus, the total amplitude is given by:

$$
\begin{aligned}
A_n\left(\tau_1,\cdots,\tau_n\right)&\sim e^{-nS_\mathrm{inst}/\hbar}\prod_{i=1}^n e^{-\omega \tau_i/2}\\
&=e^{-nS_\mathrm{inst}/\hbar} e^{-\omega \tau/2}\\
G(a,\pm a;\tau)&\simeq \sum_{n\mathrm{\;even/odd}}K^n e^{-nS_\mathrm{inst}/\hbar} e^{-\omega \tau/2}\int_0^\tau d\tau_1 \int_0^{\tau_1} d\tau_2 \cdots \int_0^{\tau_{n-1}} d\tau_{n}\\
&= e^{-\omega \tau/2}\sum_{n\mathrm{\;even/odd}}K^n e^{-nS_\mathrm{inst}/\hbar} \frac{\tau^n}{n!}\\
&= e^{-\omega \tau/2}\sum_{n\mathrm{\;even/odd}} \frac{\left(K\tau e^{-S_\mathrm{inst}/\hbar}\right)^n}{n!}\\
\end{aligned}
$$

Finally, we obtain the transition amplitude:
$$G(a,a;\tau)\simeq Ce^{-\omega \tau/2}\cosh{\left(K\tau e^{-S_\mathrm{inst}/\hbar}\right)}$$
$$G(a,-a;\tau)\simeq Ce^{-\omega \tau/2}\sinh{\left(K\tau e^{-S_\mathrm{inst}/\hbar}\right)}$$

where $C$ is some factor that depends in a non-exponential way on the transition time.