---
title: "Periodic Quantum System in the Instanton Picture"
subtitle: "Condensed Matter Field Theory > Chapter3 > Problem 3.6"
---

In this website, I will confirm that the propagator of a quantum periodic system is compatible with the Bloch function and its spectrum.

## Question

:::{.alert .alert-info}

1. A quantum mechanical particle moves in a periodic lattice potential $V$ with period $a$. 
Taking the Euclidean action for the instanton connecting two neighboring minima to be $S_{\rm inst}$, express the Euclidean time propagator $G(ma,na;\tau)$, with $m$ and $n$ integer, as a sum over instanton and anti-instanton field configurations.

1. Making use of the identity 
$$\delta_{qq'} = \frac{1}{2π}\int_0^{2\pi} d\theta\, e^{i(q−q')\theta}$$
show that
$$
G(ma,na;\tau) \sim e^{-\omega \tau/2}\int_0^{2\pi} \frac{d\theta}{2\pi} \,e^{i(n-m)\theta} e^{\frac{\Delta \epsilon \tau}{\hbar }2\cos{\theta}}.
$$

1. Keeping in mind that, in the periodic system, the eigenfunctions are Bloch states
$\psi_{p\alpha}(q) = e^{ipq}u_{p\alpha}(q)$ where $u_{p\alpha}(q+ma) = u_{p\alpha}(q)$ denotes the periodic part of the Bloch function, show that the propagator is compatible with a spectrum of the lowest band 
$$\alpha = 0,\;\epsilon_p = \frac{\hbar \omega}{2} − 2\Delta \epsilon \cos{pa}.$$

:::

## Strategy

* Recall the formula for the instanton action $S_{\rm inst}$ and the instanton propagator $G_{\rm inst}$.


## Solution

### Propagator $G(ma,na;\tau)$

We learned that the most effective configurations of the Euclidean action involved consecutive sequences of instanton--anti-instanton pairs in the double-well potential.
However, in the periodic system, because of the boundary condition, the difference in the number of instantons and anti-instantons must be congruent to the number of potential units passed. Let the number of instantons be $q$ and let the number of anti-instantons be $q'$, then $q-q'=n-m$ must be satisfied.

Recall the formula for the propagator in the double-well potential. In this case, the calculation can be done simply by changing the way instantons are taken.
First, approximate the contribution from staying in the bottom of the potential $\sqrt{1/\sinh{\omega\tau}}\simeq e^{-\omega\tau/2}$ (instanton gas). 
The contribution from $n$ (anti-)instantons can be written as 
$$G(\mathrm{[path]};\tau)\sim \sum_{n:\mathrm{allowed}} \frac{\left(\tau K e^{-S_\mathrm{inst}/\hbar}\right)^n}{n!}.$$

$n$ is the number of instantons and anti-instantons, but what we should take into account is the particle can move along the path in $n$ steps.
For ease, we neglect this annoying fact until we get the complete form of the propagator.

The contribution from $q$ instantons and $q'$ anti-instantons can be written as
$$G(ma,na;\tau)\sim \sum_{q,q':\mathrm{allowed}} \frac{\left(\tau K e^{-S_\mathrm{inst}/\hbar}\right)^{q+q'}}{q!q'!}.$$

By considering all of the aforementioned factors, we obtain the following

$$G(ma,na;\tau)\sim e^{-\omega \tau/2}\sum_{q,q':\mathrm{allowed}} \frac{\left(\tau K e^{-S_\mathrm{inst}/\hbar}\right)^{q+q'}}{q!q'!}.$$

Finally, we limit the index of sum:

$$G(ma,na;\tau)\sim e^{-\omega \tau/2}\sum_{q,q'}\delta_{q-q',n-m} \frac{\left(\tau K e^{-S_\mathrm{inst}/\hbar}\right)^{q+q'}}{q!q'!}.$$

### Rewriting the propagator

Substituing $\delta_{q-q',m-n}$ for $\delta_{q-q',m-n} = \frac{1}{2π}\int_0^{2\pi} d\theta\, e^{i(q−q'-n+m)\theta}$, we obtain the following result:

$$
\begin{aligned}
G(ma,na;\tau)
&\sim e^{-\omega \tau/2}\sum_{q,q'}\int_0^{2\pi} \frac{d\theta}{2\pi} \,e^{i(q-q'-n+m)\theta} \frac{\left(\tau K e^{-S_\mathrm{inst}/\hbar}\right)^{q+q'}}{q!q'!}\\
&\sim e^{-\omega \tau/2}\int_0^{2\pi} \frac{d\theta}{2\pi} \,e^{-i(n-m)\theta} \sum_{q}\frac{\left(\tau K e^{i\theta}e^{-S_\mathrm{inst}/\hbar}\right)^{q}}{q!}\sum_{q'}\frac{\left(\tau K e^{-i\theta}e^{-S_\mathrm{inst}/\hbar}\right)^{q'}}{q'!}\\
&\sim e^{-\omega \tau/2}\int_0^{2\pi} \frac{d\theta}{2\pi} \,e^{-i(n-m)\theta} \exp{\left(\tau K e^{i\theta}e^{-S_\mathrm{inst}/\hbar}\right)}\exp{\left(\tau K e^{-i\theta}e^{-S_\mathrm{inst}/\hbar}\right)}\\
\end{aligned}
$$
Let $\Delta \epsilon:=\hbar K \exp{\left(-S_\mathrm{inst}/\hbar \right)}$. Then:
$$
\begin{aligned}
G(ma,na;\tau)
&\sim e^{-\omega \tau/2}\int_0^{2\pi} \frac{d\theta}{2\pi} \,e^{-i(n-m)\theta} \exp{\left(\tau K e^{i\theta}e^{-S_\mathrm{inst}/\hbar}\right)}\exp{\left(\tau K e^{-i\theta}e^{-S_\mathrm{inst}/\hbar}\right)}\\
&\sim e^{-\omega \tau/2}\int_0^{2\pi} \frac{d\theta}{2\pi} \,e^{-i(n-m)\theta} \exp{\left(\frac{\Delta \epsilon\tau}{\hbar}  e^{i\theta}\right)}\exp{\left(\frac{\Delta \epsilon\tau}{\hbar}e^{-i\theta}\right)}\\
&\sim \int_0^{2\pi} \frac{d\theta}{2\pi} \,e^{-i(n-m)\theta} \exp{\left(-\omega \tau/2+2\frac{\Delta \epsilon\tau}{\hbar} \cos{\theta}\right)}
\end{aligned}
$$

### Compatibility with the Bloch theory

Assume the system is periodic and Hamiltonian satisfies $H|p\rangle=\epsilon_p|p\rangle$.
The original definition of the propagator is $G(ma,na,\tau)=\langle na|e^{-\tau H/\hbar}|ma\rangle$. In the words of Bloch's theory, the propagator is written as follows:

$$
\begin{aligned}
G(ma,na,t)&=\langle na|e^{-\tau H/\hbar}|ma\rangle\\
&=\sum_p \langle na|p\rangle e^{-\tau \epsilon_p/\hbar}\langle p|ma\rangle\\
&=\sum_p \psi_p(na) e^{-\tau \epsilon_p/\hbar}\psi^*_p(ma)\\
&=\sum_p |\psi_p(0)|^2e^{-\tau \epsilon_p/\hbar+ip\left(n-m\right)a}\\
\end{aligned}
$$

The correspondence with the results of the previous problem is as follows:

$$
\begin{aligned}
\int \,dp&\leftrightarrow \sum_p\\
\theta &\leftrightarrow -pa\\
\epsilon_p &\leftrightarrow \frac{\hbar \omega}{2}-2\Delta \epsilon\cos{pa}\\
\end{aligned}
$$

## References

* [Condensed Matter Field Theory, 2nd edition, by Alexander Altland and Ben Simons](https://www.cambridge.org/core/books/condensed-matter-field-theory/0A8DE6503ED868D96985D9E7847C63FF)