---
title: "Path integral for a quantum harmonic oscillator"
subtitle: "Condensed Matter Field Theory > Chapter 3 > Problem 2"
---

In this webpage, we will derive the density matrix for a quantum harmonic oscillator at finite temperature using the path integral formalism.

## Question

:::{.alert .alert-info}

Consider a quantum harmonic oscillator:

$$H=\frac{p^2}{2m}+\frac{1}{2}m\omega^2 q^2$$

Obtain the density matrix $\rho(q,q')=\langle q|e^{-\beta H}|q'\rangle$ at finite temperature, where $\beta=1/T\,(k_B=1)$. Obtain and comment on the asymptotics:

1. Low temperature: $T\ll \hbar \omega$
1. High temperature: $T\gg \hbar \omega$

In the high-temperature case, be sure to carry out the expansion in $\hbar \omega/T$ to second order.

:::

## Strategy

* The path integral for the classical harmonic oscillator derives the propagator.
* Imaginary time evolution of the propagator gives the density matrix.


## Solution

### Matrix elements of the density matrix

Consider a path integral for the classical harmonic oscillator.
The action is written as:
$$S[q]=\int_0^t dt' \frac{m}{2}\left(\dot{q}^2-\omega^2 q^2\right).$$

The corresponding propagator is given by the path integral:

$$\langle q|e^{-iHt/\hbar }|q'\rangle=\int_{q(0)=q}^{q(t)=q'} \mathcal{D}q\,e^{iS[q]/\hbar}$$

where $\mathcal{D}q$ is the path integral measure.

Calculating the path integral, we obtain the propagator[^whypropagater]:

[^whypropagater]: Please see the problem 3-1 of the book for the derivation of the propagator.

$$\langle q|e^{-iHt/\hbar }|q'\rangle=\left(\frac{m\omega}{2\pi i\hbar \sin{\omega t}}\right)^{\frac{1}{2}}\exp\left[i\frac{m\omega}{2\hbar}\left(\left(q^2+q'^2\right)\cot{\omega t}-\frac{2q q'}{\sin{\omega t}}\right)\right]$$

To obtain matrix elements of the density matrix, consider the imaginary time evolution: $t=-i\beta\hbar$. We obtain the density matrix:

$$\langle q|e^{-\beta H }|q'\rangle=\left(\frac{m\omega}{2\pi\hbar \sinh{\beta\hbar\omega}}\right)^{\frac{1}{2}}\exp\left[-\frac{m\omega}{2\hbar}\left(\left(q^2+q'^2\right)\coth{\beta\hbar\omega}-\frac{2q q'}{\sinh{\omega \beta\hbar}}\right)\right].$$

### Low temperature expansion

In the low-temperature limit, $\beta\hbar\omega\gg 1,\, \coth{\beta\hbar\omega}\approx 1,\, \sinh{\omega \beta\hbar}\approx e^{\beta\hbar\omega}/2$. We obtain:

$$\langle q|e^{-\beta H }|q'\rangle=\rho(q,q')=\left(\frac{m\omega}{\pi\hbar e^{\beta\hbar\omega}}\right)^{\frac{1}{2}}\exp\left[-\frac{m\omega}{2\hbar}\left(\left(q^2+q'^2\right)-\frac{2q q'}{e^{\beta\hbar\omega}}\right)\right]$$

$$\to \left(\frac{m\omega}{\pi\hbar e^{\beta\hbar\omega}}\right)^{\frac{1}{2}}\exp\left[-\frac{m\omega}{2\hbar}\left(q^2+q'^2\right)\right].$$

Remember that following holds for the harmonic oscillator:

$$p(q)=\left|\langle q|n=0\rangle\right|^2\propto e^{-\frac{m\omega}{\hbar}q^2}$$

Therefore, matrix element can be rewritten as:

$$\rho(q,q')=\langle q|n=0\rangle e^{-\beta E_0}\langle n=0|q'\rangle=\psi^*(q)e^{-\beta E_0}\psi(q').$$

In the low-temperature limit, the wave function of the ground state appears and quantum nature becomes apparent. This fact is consistent with the fact that probabilities are concentrated in the ground state at low temperatures.

### High temperature expansion

In the high-temperature limit, $\beta\hbar\omega\ll 1,\, \coth{\beta\hbar\omega}\approx 1/x+x/3,\, 1/\sinh{\omega \beta\hbar}\approx 1/x-x/6$. We obtain:

$$\langle q|e^{-\beta H }|q'\rangle\approx\left(\frac{m}{2\pi\beta\hbar^2}\right)^{\frac{1}{2}}\exp\left[-\frac{m\omega}{2\hbar}\left(\left(q^2+q'^2\right)\left(\frac{1}{\beta\hbar\omega}+\frac{\beta\hbar\omega}{3}\right)-2q q'\left(\frac{1}{\beta\hbar\omega}-\frac{\beta\hbar\omega}{6}\right)\right)\right]$$

$$=\left(\frac{m}{2\pi\beta\hbar^2}\right)^{\frac{1}{2}}\exp\left[-\frac{m\omega}{2\hbar}\left(\frac{(q-q')^2}{\beta\hbar\omega}+\frac{\beta\hbar\omega}{3}\left(q^2+q'^2+qq'\right)\right)\right]$$

$$= \left(\frac{m}{2\pi\beta\hbar^2}\right)^{\frac{1}{2}}e^{-\frac{m(q-q')^2}{\beta\hbar^2}}\quad\times \quad\exp\left[-\frac{m\beta\omega^2}{6}\left(q^2+q'^2+qq'\right)\right]$$

$$\approx \delta(q-q')\exp{\left[-\beta\frac{m\omega^2}{6}\left(q^2+q'^2+qq'\right)\right]}$$

$$= \delta(q-q')e^{-\beta\frac{m\omega^2q^2}{2}}.$$

In the high-temperature limit, the Maxwell-Boltzmann distribution appears, indicating that thermal properties become apparent. Unlike quantum mechanics, where position and momentum can be determined independently, this matrix element of the density matrix can be thought of as already integrated for momentum.

## References

* [Condensed Matter Field Theory, 2nd edition, by Alexander Altland and Ben Simons](https://www.cambridge.org/core/books/condensed-matter-field-theory/0A8DE6503ED868D96985D9E7847C63FF)