---
title: "Foundations of Information Geometry"
bibliography: AppGeom_files/ref.bib
---

This note is a memorandum about the mathematical knowledge necessary for understanding information geometry. The contents of this note might be wrong. If you find any mistakes, please let me know. Almost all of the contents of this note are based on @AkioFujiwara2021.

# Riemannian Metric

## Definition

Let $M$ be a smooth manifold. A **Riemannian metric** on $M$ is a smooth map $g: \mathfrak{X}(M) \times \mathfrak{X}(M) \to C^\infty(M)$ satisfying the following properties:

1. $g(X,Y) = g(Y,X)$ for all $X,Y \in \mathfrak{X}(M)$.
2. $g(X,X) \geq 0$ for all $X \in \mathfrak{X}(M)$.
3. $g(X,X) = 0$ if and only if $X = 0$.

## Riemannian Metric (Defined by a Coordinate System)

Let $M$ be a smooth manifold. Let $\{x^i\}$ be a coordinate system on $M$. The map $g: \mathfrak{X}(M) \times \mathfrak{X}(M) \to C^\infty(M)$ defined by

$$
g(X,Y) = \sum_{i,j=1}^n g_{ij}X^iY^j
$$

for all $X,Y \in \mathfrak{X}(M)$ is a Riemannian metric on $M$ if and only if the matrix $(g_{ij})$ is positive definite.

## Geodesic (Defined by a Riemannian Metric)

Let $(M,g)$ be a Riemannian manifold. A smooth curve $\gamma: [a,b] \to M$ is said to be a **geodesic** if $\gamma$ is a critical point of the functional

$$
L(\gamma) = \int_a^b \sqrt{g(\gamma',\gamma')}dt
$$

This functional can be rewritten as

$$
L(\gamma) = \int_a^b \sqrt{g_{ij}\frac{dx^i}{dt}\frac{dx^j}{dt}}dt
$$

The critical point of this functional is a solution to the Euler-Lagrange equation

$$
\frac{d^2x^k}{dt^2} + \frac{1}{2}g^{kl}\left(
    \partial_ig_{jl} + \partial_jg_{il} - \partial_lg_{ij}
\right)\frac{dx^k}{dt}\frac{dx^l}{dt} = 0
$$

for all $i \in \{1,\dots,n\}$.


# Affine Connection

## Definition

Let $M$ be a smooth manifold. An **affine connection** on $M$ is a map $\nabla: \mathfrak{X}(M) \times \mathfrak{X}(M) \to \mathfrak{X}(M)$ satisfying the following properties:

1. $\nabla_{fX}Y = f\nabla_XY$ for all $f \in C^\infty(M)$ and $X,Y \in \mathfrak{X}(M)$.
2. $\nabla_X(fY) = f\nabla_XY + (Xf)Y$ for all $f \in C^\infty(M)$ and $X,Y \in \mathfrak{X}(M)$.
3. $\nabla_X(Y+Z) = \nabla_XY + \nabla_XZ$ for all $X,Y,Z \in \mathfrak{X}(M)$.
4. $\nabla_X(Y(f)) = (\nabla_XY)(f) + Y(Xf)$ for all $f \in C^\infty(M)$ and $X,Y \in \mathfrak{X}(M)$.

## Parallel Transport

Let $\nabla$ be an affine connection on a smooth manifold $M$. Let $\gamma: [a,b] \to M$ be a smooth curve. A vector field $V$ along $\gamma$ is said to be **parallel** if $\nabla_{\gamma'}V = 0$.

## Coefficients of a Connection

Let $\nabla$ be a connection on a smooth manifold $M$. For each $i,j,k \in \{1,\dots,n\}$, there exist unique functions $\Gamma^k_{ij}: M \to \mathbb{R}$ such that

$$
\nabla_{\partial_i}\partial_j = \sum_{k=1}^n \Gamma^k_{ij}\partial_k= \Gamma^k_{ij}\partial_k
$$

The functions $\Gamma^k_{ij}$ are called the **coefficients of the connection** $\nabla$ with respect to the coordinate system $\{x^i\}$. $\Gamma^k_{ij}$ is called the **Christoffel symbol**. Note that $\Gamma^k_{ij}$ is not a tensor field.

## Geodesic (Defined by an Affine Connection)

Let $\nabla$ be an affine connection on a smooth manifold $M$. A smooth curve $\gamma: [a,b] \to M$ is clearly satisfies the following properties:

$$
\nabla_{\gamma'}\gamma' = 0
$$

This equation can be rewritten as

$$
\frac{d^2x^k}{dt^2} + \Gamma^k_{ij}\frac{dx^i}{dt}\frac{dx^j}{dt} = 0
$$

for all $i \in \{1,\dots,n\}$.

## Levi-Civita Connection

The geodesic defined by an affine connection does not necessarily correspond to the geodesic defined by a Riemannian metric. However, if we assume that the connection is defined by the following relation

$$
\Gamma^k_{ij} = \frac{1}{2}g^{kl}\left(
    \partial_ig_{jl} + \partial_jg_{il} - \partial_lg_{ij}
\right)
$$

for all $i,j,k \in \{1,\dots,n\}$, then the geodesic defined by the affine connection is the same as the geodesic defined by the Riemannian metric. This connection is called the **Levi-Civita connection** of the Riemannian metric.

Let $(M,g)$ be a Riemannian manifold. Let $\Gamma^k_{ij}$ be the coefficients of the connection $\nabla$ with respect to the coordinate system $\{x^i\}$. The **Levi-Civita connection** $\nabla$ of $g$ is the unique connection on $M$ such that

$$
\Gamma^k_{ij} = \frac{1}{2}g^{kl}\left(
    \partial_ig_{jl} + \partial_jg_{il} - \partial_lg_{ij}
\right)
$$

for all $i,j,k \in \{1,\dots,n\}$.

## Dual Affine Connection

Let $(M,g)$ be a Riemannian manifold. The **dual affine connection** $\nabla^*$ of the connection $\nabla$ is the unique affine connection on $M$ such that

$$
Xg(Y,Z) = g(\nabla_XY,Z) + g(Y,\nabla^*_XZ)
$$

for all $X,Y,Z \in \mathfrak{X}(M)$. $(g,\nabla,\nabla^*)$ is called a **dual structure** on $M$.

The dual structure $(g,\nabla,\nabla^*)$ satisfies the following properties:

$$
\partial_kg_{ij}=\Gamma_{kij}+\Gamma^*_{kji}
$$

where $\Gamma_{kij}$ and $\Gamma^*_{kji}$ are the coefficients of the connection $\nabla$ and $\nabla^*$ with respect to the coordinate system $\{x^i\}$.

# Torsion and Curvature

## Torsion

Let $\nabla$ be a connection on a smooth manifold $M$. The **torsion** of $\nabla$ is the tensor field $T : \mathfrak{X}(M) \times \mathfrak{X}(M) \to \mathfrak{X}(M)$ defined by

$$
T(X,Y) = \nabla_XY - \nabla_YX - [X,Y]
$$

for all $X,Y \in \mathfrak{X}(M)$. The connection $\nabla$ is said to be **torsion-free** if $T = 0$.

## Curvature

Let $\nabla$ be a connection on a smooth manifold $M$. The **curvature** of $\nabla$ is the tensor field $R : \mathfrak{X}(M) \times \mathfrak{X}(M) \times \mathfrak{X}(M) \to \mathfrak{X}(M)$ defined by

$$
R(X,Y)Z = \nabla_X\nabla_YZ - \nabla_Y\nabla_XZ - \nabla_{[X,Y]}Z
$$

for all $X,Y,Z \in \mathfrak{X}(M)$.

## Dual Curvature

Let $(\nabla,\nabla^*)$ be a dual structure on a smooth manifold $M$. The **dual curvature** of $(\nabla,\nabla^*)$ is the tensor field $R^* : \mathfrak{X}(M) \times \mathfrak{X}(M) \times \mathfrak{X}(M) \to \mathfrak{X}(M)$ defined by

$$
R^*(X,Y)Z = \nabla^*_X\nabla^*_YZ - \nabla^*_Y\nabla^*_XZ - \nabla^*_{[X,Y]}Z
$$

for all $X,Y,Z \in \mathfrak{X}(M)$.

**$R=0$ is equivalent to $R^*=0$, but $T=0$ is not equivalent to $T^*=0$.**

# Bianchi Identities

Let $\nabla$ be a Levi-Civita connection on a Riemannian manifold $(M,g)$.

## 1st Bianchi Identity

The **1st Bianchi identity** is the identity

$$
R(X,Y)Z + R(Y,Z)X + R(Z,X)Y = 0
$$

for all $X,Y,Z \in \mathfrak{X}(M)$.

## 2nd Bianchi Identity

The **2nd Bianchi identity** is the identity

$$
\nabla_XR(Y,Z)W + \nabla_YR(Z,X)W + \nabla_ZR(X,Y)W = 0
$$

for all $X,Y,Z,W \in \mathfrak{X}(M)$.

# $\nabla$-Flat

## Definition

Let $\nabla$ be a connection on a smooth manifold $M$. The connection $\nabla$ is said to be **flat** if $R = 0$ and $T = 0$.

## $\nabla$-Affine Coordinates

Let $\nabla$ be a connection on a smooth manifold $M$. A coordinate system $\{x^i\}$ is said to be **$\nabla$-affine** if $\Gamma^k_{ij} = 0$ for all $i,j,k \in \{1,\dots,n\}$.

## Existence of Local $\nabla$-Affine Coordinates

Let $\nabla$ be a connection on a smooth manifold $M$. For each $p \in M$, there exists a neighborhood $U$ of $p$ and a $\nabla$-affine coordinate system $\{x^i\}$ on $U$.

## Dual-Flat

Let $(g,\nabla,\nabla^*)$ be a dual structure on a smooth manifold $M$. The dual structure $(g,\nabla,\nabla^*)$ is said to be **dual-flat** if $R = R^* = 0$ and $T = T^* = 0$.

# Dual Affine Coordinates

## Definition

Let $\theta^i$ be a coordinate system for a connection $\nabla$, $\eta_i$ be a coordinate system for the dual connection $\nabla^*$. The coordinate system $\{(\theta^i),(\eta^i)\}$ is called the **dual affine coordinate system**.

If the manifold $M$ is dual-flat with respect to the dual structure $(g,\nabla,\nabla^*)$, then we can choose the local dual affine coordinate system $\{(\theta^i),(\eta^i)\}$ around any point $p \in M$ that the components of the metric $g$ at $p$ satisfy 

$$
g\left(
    \frac{\partial}{\partial \theta^i}, \frac{\partial}{\partial \eta_j}
\right)
=g(\partial_i,\partial^j)
=\delta_i^j.
$$

## Properties

Let $\{(\theta^i),(\eta^i)\}$ be a dual affine coordinate system. Let $g_{ij}$, $g^{ij}$ be the components of the metric $g$ with respect to the coordinate system $\{(\theta^i),(\eta^i)\}$

$$
g_{ij} = g\left(\partial_i,\partial_j\right), \quad g^{ij} = g\left(\partial^i,\partial^j\right).
$$

Then, the following properties hold:

$$
g_{ij}=\partial_i\eta_j, \quad g^{ij}=\partial^i\theta^j, \quad g_{ik}g^{kj}=\delta^i_j.
$$

## Potential Functions

There exists a function $\psi(\theta),\,\varphi(\eta)$ on $M$ such that

$$
\partial_i\psi(\theta)=\eta_i, \quad \partial^i\varphi(\eta)=\theta^i.
$$

The functions $\psi(\theta),\,\varphi(\eta)$ are called the **potential functions** of the dual affine coordinate system $\{(\theta^i),(\eta^i)\}$.

The metric $g$ can be expressed as

$$
g_{ij}=\partial_i\eta_j=\partial_i\partial_j\psi(\theta), \quad g^{ij}=\partial^i\theta^j=\partial^i\partial^j\varphi(\eta).
$$

We can choose the potential functions $\psi(\theta),\,\varphi(\eta)$ so that they satisfy the following properties:

$$
\psi(\theta)+\varphi(\eta)-\theta^i\eta_i=0
$$

Let the dual affine coordinate system be $\{(\theta^i),(\eta^i)\}$ at the point $p \in M$, and let the potential functions be $\psi(\theta),\,\varphi(\eta)$. Then, the potential functions can be transformed by Legendre transformation as follows:

$$
\begin{aligned}
\psi(\theta)&=\underset{q\in M}{\mathrm{max}}\left(\eta_i(q)\theta^i(p)-\varphi(\eta(q))\right)\\
\varphi(\eta)&=\underset{q\in M}{\mathrm{max}}\left(\theta^i(q)\eta_i(p)-\psi(\theta(q))\right).
\end{aligned}
$$

## $\nabla$-Divergence

Let $\nabla$ be a connection on a smooth manifold $M$. Let $\{(\theta^i),(\eta^i)\}$ be a dual affine coordinate system. The **$\nabla$-divergence** between two points $p,q \in M$ is defined by

$$
D(p||q)=\psi(\theta(p))+\varphi(\eta(q))-\theta^i(p)\eta_i(q)
$$

where $\{(\theta),(\varphi)\}$ is the global dual affine coordinate system.

$\nabla$-divergence is invariant under the transformation of dual affine coordinate systems.

## Generalized Pythagorean Theorem

Let $\nabla$ be a connection on a smooth manifold $M$. Let $\{(\theta^i),(\eta^i)\}$ be a dual affine coordinate system. Let $p,q,r \in M$. Assume that the $\nabla$-geodesic $\gamma$ from $p$ to $q$ is perpendicular to the $\nabla^*$-geodesic $\gamma'$ from $q$ to $r$ for the metric $g$. Then, the following **generalized Pythagorean theorem** holds:

$$
D(p||r)=D(p||q)+D(q||r).
$$

# Application to Information Geometry

## Fisher Information Metric

Let $p(x;\theta)$ be a probability density function on $\mathbb{R}^n$ concerning the Lebesgue measure. The **Fisher information metric** $g$ is the Riemannian metric on the parameter space $\Theta$ defined by

$$
\begin{aligned}
g_{ij}(\theta) &= \int_{\mathbb{R}^n} p(x;\theta)\left[\frac{\partial}{\partial \theta^i} \log p(x;\theta) \frac{\partial}{\partial \theta^j} \log p(x;\theta)\right] dx\\
&= \int_{\mathbb{R}^n} \left[\frac{\partial l(x;\theta)}{\partial \theta^i}  \frac{\partial p(x;\theta)}{\partial \theta^j} \right] dx
\end{aligned}
$$

for all $\theta \in \Theta$. Here, $l(x;\theta)=\log p(x;\theta)$ is the score function.

Here, the following property holds:

$$
\begin{aligned}
\partial_kg_{ij}(\theta)&=\partial_k \int_{\mathbb{R}^n} p(x;\theta)\left[\frac{\partial}{\partial \theta^i} \log p(x;\theta) \frac{\partial}{\partial \theta^j} \log p(x;\theta)\right] dx\\
&=\int_{\mathbb{R}^n} \left[\frac{\partial^2 l(x;\theta)}{\partial \theta^k \partial \theta^i}  \frac{\partial p(x;\theta)}{\partial \theta^j} + \frac{\partial l(x;\theta)}{\partial \theta^i}  \frac{\partial^2 p(x;\theta)}{\partial \theta^k \partial \theta^j} \right] dx\\
\end{aligned}
$$

Dual affine connection is described as $\partial_kg_{ij}=\Gamma_{kij}+\Gamma^*_{kji}$. Therefore, the dual affine connection is given by

$$
\begin{aligned}
\Gamma_{kij}(\theta)&=\int_{\mathbb{R}^n} \left[\frac{\partial^2 l(x;\theta)}{\partial \theta^k \partial \theta^i}  \frac{\partial p(x;\theta)}{\partial \theta^j} \right] dx\\
\Gamma^*_{kji}(\theta)&=\int_{\mathbb{R}^n} \left[\frac{\partial l(x;\theta)}{\partial \theta^i}  \frac{\partial^2 p(x;\theta)}{\partial \theta^k \partial \theta^j} \right] dx.\\
\end{aligned}
$$

We denote $\Gamma_{kij}(\theta)$ and $\Gamma^*_{kji}(\theta)$ as $\overset{e}{\Gamma}_{kij}$ and $\overset{m}{\Gamma}_{kji}$, respectively.
Furthermore, we call them the **exponential connection(e-connection)** and the **mixture connection(m-connection)**, respectively.