---
title: "金属のゾンマーフェルト理論"
subtitle: "アシュクロフト・マーミン/上1・2章"
---

メモとして書かれているため、書籍の内容と比較すると順番が前後していることや内容の不足・多少の差異・誤植がありますのでご理解ください。また、スピンの自由度を考慮すると紛らわしくなる場合が多いので、原則としてスピンレスフェルミオンを想定しています。実際の計算ではスピンを考慮する必要がありますが、その場合は2をかけることを忘れないようにしてください。

# Maxwell-Boltzmann分布の破綻

Maxwell-Boltzmann分布は同種粒子の不可弁別性などを記述しないため、量子系で粒子密度が高くなると破綻する。
歴史的な経緯としては、以下の金属比熱の温度依存性を説明できないことが問題となった。

* 3次元空間での理想気体では粒子あたり $C=\frac{3}{2}k_B$ の比熱を与えるが、そのような寄与が存在しないのはなぜか？

量子統計力学では、粒子の不可弁別性を考慮することで、Maxwell-Boltzmann分布の破綻を回避することができる。
Fermi-Dirac統計とBose-Einstein統計の2つが存在するが、金属の電子はフェルミ粒子であるため、Fermi-Dirac統計を用いる。
Fermi-Dirac分布はエネルギー $E$ を占有するFermi粒子の数の期待値を表す：
$$
f(E)=\frac{1}{e^{\frac{E-\mu}{k_BT}}+1}
$$
ここで、$\mu$ は化学ポテンシャルである。

Maxwell-Boltzmann分布との違いは、低エネルギー側の粒子の占有数である。パウリの排他律を考慮すると、スピンレスフェルミオンは同じエネルギー準位には1つしか入れないため、低エネルギー側の粒子数はMaxwell-Boltzmann分布よりも遥かに少なくなる。

化学ポテンシャルはFermi-Dirac分布の形状を決定するパラメータとしては非常に重要であり、これをボルツマン定数で割った値は温度の次元を持つので、Maxwell-Boltzmann分布が破綻するかどうかの指標として有用である。
化学ポテンシャルは粒子数保存条件から決められるので、常に一定の値ではないが、代表的な値は約1000Kであり、これは室温よりもはるかに高いため、Maxwell-Boltzmann分布が破綻したと考察できる。

# 独立自由電子気体の集団基底状態

金属の最も簡単な近似の1つは、電子が独立自由電子気体であるというものである。
この近似では、電子は金属イオンのポテンシャルによって束縛されていると考えるのではなく、井戸型のグローバルなポテンシャルによって束縛されていないと考える。さらに、パウリの排他律を除いて相互作用の効果を無視する。

すべての電子が同一のポテンシャルの中に居るので、同じエネルギー・スピン同時固有状態は専有されない。従って各エネルギーレベルにつき2つの電子を基底状態から順に詰めていけば、これよりも安定な状態はないので、集団基底状態が得られる。

一方で、固有波動関数の境界条件は問題となる。自然な境界条件としては色々あるが、金属が1辺 $L=V^{1/3}$ の立方体であるという幾何的な仮定をおくと、周期的境界条件はあまり適当ではないが、この場合の解はよく知られたように、境界で電子の存在確率が0となるだけでなく、必ず定在波となりあまり適当ではない。従って、幾何的な仮定を多少ぞんざいに扱って、周期的境界条件を採用する。この場合、境界で波動関数は0でない値を持つことができ、進行する波を記述することもできる。

電子の固有状態は量子化された波数 $\vec{k}=\frac{2\pi \vec{n}}{\vec{L}}$ で良く特徴づけられる。エネルギー固有値も併せて以下のようになる：
$$
\begin{aligned}
\psi_{\vec{k}}(\vec{r})&=\frac{1}{\sqrt{V}}e^{i\vec{k}\cdot\vec{r}}\\
E(\vec{k})&=\frac{\hbar^2}{2m}\left(k_x^2+k_y^2+k_z^2\right)\\
\end{aligned}
$$

波数の意味について考察する。$w$ を、$x,y,z$ のいずれかを表す文字として使うと、運動量演算子を固有状態に作用させて以下を得る：
$$
\hat{p}_w\psi_{\vec{k}}(\vec{r})=\frac{\hbar}{i}\frac{\partial}{\partial w}\psi_{\vec{k}}(\vec{r})=\hbar k_w\psi_{\vec{k}}(\vec{r})
$$
つまり、波数に換算プランク定数をかけたものは、運動量に等しい。(自然単位系では、換算プランク定数は1であるから、波数と運動量は等しい。)この観点に立ってエネルギー固有値を書き直すと、以下のようになる：
$$
E(\vec{p})=\frac{p^2}{2m}
$$
つまり、エネルギー固有値は運動エネルギーを書き直しただけのものである。


さて、実際の金属ではアボガドロ数のオーダーで電子が大量に存在するため、うまく定義すれば波数 $\vec{k}$ は連続的な値を取るとみなすことができる。
波数でラベルされる状態密度の定義に取り掛かろう。
波数空間の体積は $k^3=\left(\frac{2\pi}{L}\right)^3$ が単位となっているから、体積 $\Omega$ の波数空間での領域には、$\frac{\Omega L^3}{8\pi^3}=\frac{\Omega V}{8\pi^3}$ だけの状態が詰まっている。

したがって波数空間の体積素片を $dk_xdk_ydk_z$ とすると、その領域の状態数は
$$\frac{V}{8\pi^3}dk_xdk_ydk_z$$
とみなして積分すれば良い。もちろんこれは扱う波数空間の領域が非常に大きいことを仮定しているが、物性物理の多くの場合においてこの近似が破綻するような小さな波数空間での振る舞いは興味の対象とならない。

波数の小さいものから順に状態を詰めていくのだから、最もエネルギーの高い状態(フェルミ準位 $E_F$)の電子だけを集めると波数空間でほとんど球面のようになっている。これをフェルミ面とよび、内部まで考慮する場合はフェルミ球と呼ぶ。またその半径はフェルミ波数 $k_F$ と呼ばれる。

フェルミ球の体積はすぐに $\frac{4}{3}\pi k_F^3$ と分かるから、フェルミ球の内部にあるエネルギー固有状態の数は $\frac{4}{3}\pi k_F^3\times \frac{V}{8\pi^3}=\frac{k_F^3}{6\pi^2}V$ である。
さらに、電子のスピンが1/2であることを考慮して、フェルミ球の内部にある電子の数は
$$
N=\frac{k_F^3}{3\pi^2}V
$$
と見積もることができる。
さて、物性物理をスケール不変に組み立てるには単位体積あたりの物性量を考えることが有効である。今回の場合、単位体積あたりの電子の数は $n=\frac{k_F^3}{3\pi^2}$ ということである。

フェルミ速度を非相対論的力学の知見から $v_F=\hbar k_F/m$ と定めると、この大きさはおよそ光速の1%という非常に速い速度となることが書籍では指摘されている。古典気体であれば低エネルギー側へたくさんの粒子を詰めることができるからこのようなとてつもなく速い速度は実現されず、書籍ではせいぜい平均 $10^7\rm cm/s$ 程度であると指摘されている。

典型的な金属に対する典型的な値については書籍の49ページを参照。

集団基底状態の総エネルギーは、フェルミ球の内部にある電子のエネルギーの総和であるから、スピン自由度を無視して
$$
E=\sum_{k\leq k_F}\frac{\hbar^2k^2}{2m}
$$
と書ける。ただ、これは離散化された格子について和を実行するのはなかなか大変であるから、先程から説明してきたように連続的な波数空間での積分に置き換えることを考えよう。さらに、エネルギーだけでなく一般の(波数だけに依存する)量 $F(k)$ の平均を計算することに一般化したい。状態数を波数空間の体積素片で書いた式を使えば、すぐに

$$
\langle F\rangle\simeq\sum_{k\leq k_F}F(k)=\frac{V}{8\pi^3}\int_{k\leq k_F} d^3kF(k)
$$

が得られる。$V\to \infty$ の極限でこの式は厳密になると考えられるので、

$$
\underset{V\to\infty}{\rm lim}\frac{1}{V}\langle F\rangle\simeq\frac{1}{V}\sum_{k\leq k_F}F(k)=\int_{k\leq k_F}\frac{d^3k}{8\pi^3} F(k)
$$

であると断言できる。

特に興味があるのはエネルギーの期待値である。これを計算すると
$$
\frac{\langle E\rangle}{V}=\frac{1}{8\pi^3}\int_{k\leq k_F}d^3k\frac{\hbar^2k^2}{2m}=\frac{1}{2\pi^2}\frac{\hbar^2}{2m}\int_{k\leq k_F}dk k^4=\frac{1}{2\pi^2}\frac{\hbar^2}{2m}\frac{1}{5} k_F^5
$$

ここで電子あたりのエネルギーは
$$
\frac{\langle E\rangle}{N}=\frac{\langle E\rangle/V}{N/V}=\frac{\frac{1}{2\pi^2}\frac{\hbar^2}{2m}\frac{1}{5} k_F^5}{\frac{k_F^3}{3\pi^2}}=\frac{3\hbar^2}{20m}k_F^2=\frac{3}{10}E_F
$$
である。スピン自由度を考慮すれば、
$$
\frac{\langle E\rangle}{N}=\frac{3}{5}E_F
$$
である。注目すべきは、絶対零度すなわち基底状態でこれだけのエネルギーを持っているという点にある。何度も引き合いに出しているが、Maxwell-Boltzmann分布では絶対零度で $E/N=\frac{3}{2}k_B \times 0=0$ となるが、$E_F$ は温度にして $10^4\rm K$ のオーダーであることを鑑みれば、相当な違いである。

さて、体積をパラメータとしてみなすことで、圧力を計算できる。
熱力学第一法則 $dU=TdS-pdV+\mu dN$ であるから
$$
p=-\left(\frac{\partial U}{\partial V}\right)_{S,N}=-\frac{3}{5}N\frac{\partial E_F}{\partial V}
$$
ここで $E_F=\frac{\hbar^2k_F^2}{2m}=\frac{\hbar^2}{2m}\left(\frac{N}{3\pi^2V}\right)^{2/3}$ を用いて

$$
\begin{aligned}
p&=-\frac{3}{5}N\frac{\partial E_F}{\partial V}\\
&=-\frac{3}{5}N\frac{\partial}{\partial V}\left(\frac{\hbar^2}{2m}\left(\frac{N}{3\pi^2V}\right)^{2/3}\right)\\
&=\frac{3}{5}\frac{N}{V}\frac{\hbar^2}{2m}\left(\frac{2}{3}\right)\left(\frac{N}{3\pi^2V}\right)^{2/3}\\
&=\frac{3}{5}\left(\frac{2}{3}\right)\frac{N}{V}E_F\\
&=\frac{2}{3}\frac{\langle E\rangle}{V}
\end{aligned}
$$

を導く。他にも圧縮率、あるいはその逆数なので等価ではあるが、体積弾性率 $B$を計算することもできる。
$$
\begin{aligned}
B&=-V\left(\frac{\partial p}{\partial V}\right)_{S,N}\\
&=-V\frac{2}{3}\frac{\partial }{\partial V}\frac{\langle E\rangle}{V}\\
&=-V\frac{2}{3}\frac{3N}{5}\frac{\hbar^2}{2m}\frac{\partial }{\partial V}\frac{1}{V}\left(\frac{N}{3\pi^2V}\right)^{2/3}\\
&=\frac{2}{3}\frac{3}{5}\frac{5}{3}\frac{N}{V}\frac{\hbar^2}{2m}\left(\frac{N}{3\pi^2V}\right)^{2/3}\\
&=\frac{5}{3}\frac{2\langle E\rangle}{3V}\\
&=\frac{5}{3}p=\frac{2}{3}nE_F
\end{aligned}
$$

典型的な金属に対する体積弾性率は書籍を参照。


# 熱的性質

一般の温度の場合は集団基底状態ではない。この場合はFD分布を使うことは常識であるから省略する。ただし化学ポテンシャルの扱いについては誰もが一度は混乱するところであるから補足しておきたい。

FD分布の化学ポテンシャルは粒子数と温度に依存する。もしこれらの値が与えられているならば(カノニカル分布 $(T,V,N)$ に相当)、化学ポテンシャルはFD分布の規格化条件を満たすように設計せねばならない。

特に絶対零度の場合はFD分布がステップ関数となることは先に見たとおりであり、これが成り立つためには絶対零度での化学ポテンシャルは常にフェルミエネルギーに等しくなければならないが、これは深刻な誤解を生む可能性がある。化学ポテンシャルは、後で見るように殆どの金属で温度によらずほぼ一定となるが、厳密に一定となるのはグランドカノニカル分布の場合であって、カノニカル分布の場合は規格化条件を受けて変化するから、温度が変わってもフェルミ準位上での粒子数の期待値が必ず0.5になるわけではないということを意識しておくべきである。

さて、FD分布の説明は十分であると思うから、一般の物理量 $F(k)$ の期待値について議論する。すぐに以下のように書けることが分かる：

$$
\langle F\rangle=\int \frac{d^3k}{8\pi^3}F(k)f(E(k))
$$

ここで $f(E(k))$ はFD分布である。例えば電子密度の場合は波数積分をエネルギー積分に変換することで

$$
\begin{aligned}
n&=\int \frac{d^3k}{8\pi^3}f(E(k))\\
&=\int_0^\infty \frac{dk}{2\pi^2}k^2f(E(k))\\
&=\int_0^\infty \frac{dE}{4\pi^2}\left(\frac{2m}{\hbar^2}\right)^{3/2}E^{1/2}f(E)\\
&=\int_0^\infty dE\frac{m}{2\hbar^2 \pi^2}\sqrt{\frac{2mE}{\hbar^2}}f(E)
\end{aligned}
$$

と計算していく。問題は0でない温度でFD分布が複雑な形状を持つため、積分が解析的に計算できないことである。しかし既に見たように、室温程度ではほとんどの金属ではフェルミ分布はステップ関数に近い形状を持つから、絶対零度からの摂動によって近似的に積分を実行するのは有効な手段である。形状の変化がもっとも深刻なのは化学ポテンシャル付近なのだから、何か期待値を取りたい物理量があるときは、エネルギーの関数として化学ポテンシャル付近で激しい変化をしないという要請が必要になる。これを満たす物理量を $H(E)$ とおき、負の無限大のエネルギーからの $H(E)$ の積分を $K(E)$ とおく。つまり $K(E)=\int_{-\infty}^E H(E') dE'$ となるような関数を考える。すると

$$
\begin{aligned}
\langle H\rangle&=\int_{-\infty}^\infty dE H(E)f(E)\\
&=\int_{-\infty}^\infty dE \frac{dK}{dE}f(E)\\
&=\left[K(E)f(E)\right]_{-\infty}^\infty-\int_{-\infty}^\infty dE K(E)\frac{df}{dE}\\
&=-\int_{-\infty}^\infty dE K(E)\frac{df}{dE}
\end{aligned}
$$
ここで $\frac{df}{dE}$ はFD分布の微分であり化学ポテンシャルを中心にして偶関数であるから、$K(E)$ の冪展開

$$
K(E)=K(\mu)+\sum_{n=1}^\infty \frac{1}{n!}\left.\frac{d^nK}{dE^n}\right|_{E=\mu}(E-\mu)^n
$$

のうち、奇数次の項は消える。したがって

$$
\begin{aligned}
\langle H\rangle&=-\int_{-\infty}^\infty dE K(E)\frac{df}{dE}\\
&=-K(\mu)\int_{-\infty}^\infty dE \frac{df}{dE}-\sum_{n=1}^\infty \frac{1}{n!}\left.\frac{d^nK}{dE^n}\right|_{E=\mu}\int_{-\infty}^\infty dE (E-\mu)^n\frac{df}{dE}\\
&=K(\mu)-\sum_{n=1}^\infty \frac{1}{(2n)!}\left.\frac{d^{2n}K}{dE^{2n}}\right|_{E=\mu}\int_{-\infty}^\infty dE (E-\mu)^{2n}\frac{df}{dE}\\
&=K(\mu)-\sum_{n=1}^\infty \frac{1}{(2n)!}\left.\frac{d^{2n-1}H}{dE^{2n-1}}\right|_{E=\mu}\int_{-\infty}^\infty dE (E-\mu)^{2n}\frac{df}{dE}
\end{aligned}
$$

ここで置換 $\beta(E-\mu)=x$ を行うと

$$
\begin{aligned}
\langle H\rangle&=K(\mu)-\sum_{n=1}^\infty \frac{1}{(2n)!}\left.\frac{d^{2n-1}H}{dE^{2n-1}}\right|_{E=\mu}\int_{-\infty}^\infty dE (E-\mu)^{2n}\frac{df}{dE}\\
&=K(\mu)+\sum_{n=1}^\infty \left.\frac{d^{2n-1}H}{dE^{2n-1}}\right|_{E=\mu}\left(k_B T\right)^{2n}\int_{-\infty}^\infty dx\frac{x^{2n}}{(2n)!}\left(-\frac{df}{dx}\right)
\end{aligned}
$$

ここで $f(x)=\frac{1}{e^x+1}$ である。積分の部分を $I_n$ とおく：

$$
\begin{aligned}
I_n&=\int_{-\infty}^\infty dx\frac{x^{2n}}{(2n)!}\left(-\frac{df}{dx}\right)
\end{aligned}
$$

この積分はリーマンゼータ関数に帰着され、FD分布の微分が偶関数であることを用いて積分範囲を半分にして

$$
\begin{aligned}
I_n&=\int_{-\infty}^\infty dx\frac{x^{2n}}{(2n)!}\left(-\frac{df}{dx}\right)\\
&=2\int_0^\infty dx\frac{x^{2n}}{(2n)!}\left(-\frac{df}{dx}\right)\\
&=-2\left[\frac{x^{2n}}{(2n)!}\left(-f\right)\right]_0^\infty+4n\int_0^\infty dx\frac{1}{(2n)!}x^{2n-1}f\\
&=4n\int_0^\infty dx\frac{1}{(2n)!}x^{2n-1}f\\
&=\frac{4n}{(2n)!}\int_0^\infty dx x^{2n-1}\frac{1}{e^x+1}\\
&=\frac{4n}{(2n)!}\int_0^\infty dx x^{2n-1}\frac{e^{-x}}{1+e^{-x}}\\
&=\frac{4n}{(2n)!}\int_0^\infty dx x^{2n-1}\sum_{m=0}^\infty (-1)^m e^{-(m+1)x}\\
&=\frac{4n}{(2n)!}\sum_{m=0}^\infty (-1)^m \int_0^\infty dx x^{2n-1} e^{-(m+1)x}\\
&=\frac{4n}{(2n)!}\sum_{m=0}^\infty (-1)^m \frac{(2n-1)!}{(m+1)^{2n}}\\
&=2\sum_{m=0}^\infty \frac{(-1)^m}{(m+1)^{2n}}\\
&=\left(2-2^{1-2n}\right)\zeta(2n)
\end{aligned}
$$

である。$\zeta (2n)$ の値は小さな $n$ に対しては知られており、$n=1$ から順に

$$
\begin{aligned}
\zeta(2)&=\frac{\pi^2}{6}\\
\zeta(4)&=\frac{\pi^4}{90}\\
\zeta(6)&=\frac{\pi^6}{945}\\
\zeta(8)&=\frac{\pi^8}{9450}\\
\zeta(10)&=\frac{\pi^{10}}{93555}\\
\end{aligned}
$$

である。これを用いて

$$
\begin{aligned}
\langle H\rangle&=K(\mu)+\sum_{n=1}^\infty \left.\frac{d^{2n-1}H}{dE^{2n-1}}\right|_{E=\mu}\left(k_B T\right)^{2n}\int_{-\infty}^\infty dx\frac{x^{2n}}{(2n)!}\left(-\frac{df}{dx}\right)\\
&=K(\mu)+\sum_{n=1}^\infty \left.\frac{d^{2n-1}H}{dE^{2n-1}}\right|_{E=\mu}\left(k_B T\right)^{2n}\left(2-2^{1-2n}\right)\zeta(2n)
\end{aligned}
$$

という展開を得る。よく使う形は3次までの展開である：

$$
\begin{aligned}
\langle H\rangle&\simeq K(\mu)+\frac{\pi^2}{6}\left.\frac{dH}{dE}\right|_{E=\mu}\left(k_B T\right)^2+\frac{7\pi^4}{360}\left.\frac{d^3H}{dE^3}\right|_{E=\mu}\left(k_B T\right)^4
\end{aligned}
$$

さて、これを用いて電子エネルギーおよび電子数密度を計算する。まず、波数からエネルギーへのヤコビアンを

$$g(E)=\frac{m}{2\hbar^2\pi^2}\sqrt{\frac{2mE}{\hbar^2}}$$

と定義しておいて、電子数密度は

$$
\begin{aligned}
n&=\int_{-\infty}^\infty dE g(E)f(E)\\
&\simeq \int_{-\infty}^\mu dE g(E)+\frac{\pi^2}{6}g'(E_F)\left(k_B T\right)^2
\end{aligned}
$$

電子エネルギーは

$$
\begin{aligned}
E&=\int_{-\infty}^\infty dE g(E)Ef(E)\\
&\simeq \int_{-\infty}^\mu dE g(E)E+\frac{\pi^2}{6}\left[g'(E_F)E_F+g(E_F)\right]\left(k_B T\right)^2
\end{aligned}
$$

となる。ここで化学ポテンシャルまでの積分は、フェルミエネルギーと化学ポテンシャルが有限の温度でもほぼ等しいので

$$
\begin{aligned}
\int_{-\infty}^\mu dE H(E)&=\int_{-\infty}^{E_F} dE H(E)+(\mu-E_F)H(E_F)
\end{aligned}
$$

としてもよい。この仮定のもとで化学ポテンシャルの温度依存性を計算することもできる。電子数密度をこの方法で書き直すと

$$
\begin{aligned}
n&=\int_{-\infty}^\infty dE g(E)f(E)\\
&\simeq \int_{-\infty}^{E_F} dE g(E)+(\mu-E_F)g(E_F)+\frac{\pi^2}{6}g'(E_F)\left(k_B T\right)^2
\end{aligned}
$$

となる。第一項は基底状態の電子数密度そのものであるから、左辺と右辺第一項がキャンセルして

$$
\begin{aligned}
\mu&=E_F-\frac{\pi^2}{6}\left(k_B T\right)^2\frac{g'(E_F)}{g(E_F)}\\
&=E_F-\frac{\pi^2}{6}\left(k_B T\right)^2\ln{g(E)}'|_{E_F}\\
&=E_F-\frac{\pi^2}{6}\left(k_B T\right)^2\frac{1}{2E_F}\\
&=E_F\left(1-\frac{1}{3}\left(\frac{\pi k_B T}{2E_F}\right)^2\right)
\end{aligned}
$$

となる。室温では大抵の場合ズレが0.01%に収まる。

同様の近似で電子エネルギーを計算してみる。

$$
\begin{aligned}
E&=\int_{-\infty}^\infty dE g(E)Ef(E)\\
&\simeq \int_{-\infty}^{E_F} dE g(E)E+E_F(\mu-E_F)+\frac{\pi^2}{6}\left[g'(E_F)E_F+g(E_F)\right]\left(k_B T\right)^2
\end{aligned}
$$

右辺第2項と第3項括弧内の第1項は先程の議論から0となり

$$
\begin{aligned}
E&\simeq \int_{-\infty}^{E_F} dE g(E)E+\frac{\pi^2}{6}g(E_F)\left(k_B T\right)^2\\
&=E_F+\frac{\pi^2}{6}g(E_F)\left(k_B T\right)^2
\end{aligned}
$$

となる。

重要な物理量として比熱が存在するが、熱力学での取り扱いは以下のようなものだった：

$$
\begin{aligned}
C=\frac{\partial E}{\partial T}=T\frac{\partial S}{\partial T}
\end{aligned}
$$

この表式は、エントロピーの温度に対する依存性を比熱と紐付けている。エントロピーは系の内部自由度に強く依存する。内部自由度の指標としては、古典系であれば正準座標の数、量子系であればヒルベルト空間の次元などが考えられる。
こういった内部自由度は複合系では加法的であるから、比熱を議論する際にはどういった内部自由度から寄与が発生しているか明確にする必要がある。

今回は電子気体について扱ってきたので、内部自由度は量子力学的な電子の運動の自由度に等しい。電子気体の比熱は計算できて、

$$
\begin{aligned}
C&=\frac{\partial E}{\partial T}\\
&=\frac{\pi^2}{3}k_B^2Tg(E_F)
\end{aligned}
$$

と書ける。これは純粋な電子気体の比熱が温度に比例することを表す。

実際の金属では、高温側ではイオンの運動が支配的になり $T^3$ に比例する比熱となる。これをしばしば以下の表式で表す：

$$
\begin{aligned}
C&=\gamma T+A T^3
\end{aligned}
$$

実際の金属を測定して係数を求めたい場合にしばしば行われるのは、
全体を温度で割って、絶対零度まで外挿して比熱の切片を $\gamma$ とする操作である。$\gamma$ の典型的な値については書籍を参照されたい。

# 金属伝導のSommerfeld理論

金属中の電子に対する速度分布を見たい。
点 $k$ の周りに体積 $dk_x dk_y dk_z$ の小さな体積素片を考える。
体積素片中の電子の数は

$$\frac{V}{8\pi^3}dk_x dk_y dk_z $$

である。FD分布によってこれらの状態の占有率を加味して

$$\frac{V}{8\pi^3}dk_x dk_y dk_z f(E(k)) $$

が電子数となる。波数ベクトルと速度ベクトルは自由電子モデルでは $v=\frac{\hbar k}{m} $ で結びつくから、実空間での単位体積あたりの速度分布は

$$\frac{m^3}{8\pi^3\hbar^3}dv_x dv_y dv_z f(E(v))$$

ただし
$$f(v)=\frac{1}{e^{\beta\left(\frac{mv^2}{2}-\mu\right)}+1}$$

である。

Sommerfeldは、Maxwell-Boltzmann分布をFermi-Dirac分布で置き換えることでDrudeモデルを再構築した。

しかし、古典力学を量子力学を用いて語る場合は注意が必要になる。
古典力学における正準座標の間には、量子力学では交換関係すなわち不確定性が発生する。古典力学では相空間(x,p)上の分布として密度関数 $\rho(x,p,t)$ を定義し、これのLiouville理論がそのダイナミクスを与えるが、古典力学ではこの分布を $x,p$ 両方ともデルタ関数的にすることが可能である。これは同時確定可能などと呼ばれる。一方で量子力学では、不確定性原理によって同時確定は不可能である。(このことは、古典力学の相空間上の分布 $\rho(x,p,t)$ が量子力学ではWigner関数 $W(x,p,t)$ として定義されることによって表現される。)

フェルミ波数よりも遥かに小さい領域でどれほどの位置のゆらぎがあるのか計算してみると、不確定性原理から、

$$ \Delta x \sim \frac{\hbar}{\Delta p }\ll \frac{1}{k_F}\sim r_s $$

ここで $r_s$ は平均原子間距離の程度、即ちオングストローム程度になることが多い。故にもし原子距離内の電子を記述する場合は古典論はほとんど破綻している。
しかし金属電子はイオンにトラップされておらず自由に動き回れるので、このような事情はたいてい問題とならない。逆に、位置についての詳細な知識が必要になるのは以下の2つの場合であろう：

1. 空間的に一様ではない場が加わっているとき
    * この場合であっても、オングストローム程度で場が変化する場合でなければ古典論を疑う理由にならない。問題なのは、とても波長が短い光を照射する場合など。
1. Drude理論において平均自由行程がオングストローム(の1/10)程度になる場合
    * 不確定性原理からこのような状態は位置と運動量が同時確定できないので、古典論は破綻する。このような状態を記述するためには、量子力学的な取り扱いが必要になる。

FD分布を用いたDrude理論が2番の場合においても有効であるかは自明ではないが、相互作用のない電子系について考えているので、独立な1電子において有効であると考えられる古典論の適用は多体であってもある程度の有効性が期待される。しかし、速度分布の知識を用いて何らかの量を計算する場合はかなりあからさまに量子論の補正を受ける：

* 平均自由行程
    * 代表的な電子速度の尺度はフェルミ速度であると考えられるが、そこから平均自由行程は $l=\frac{r_s/a_0}{\rho_\mu}\times \mathrm{92\overset{o}{A}}$ となる(第一章1.8式参照)。室温においても平均自由行程は100オングストローム程度になりうる。
* 熱伝導度
    * 熱伝導度を1.51式によって $\kappa=\frac{1}{3}v^2\tau c_v$ とすると、これは我々が今回導いた表示に比べて $k_B T/E_F$ 程度の因子で小さい。平均2乗速度が古典的でなくてフェルミ速度程度であるとすれば $\beta E_F$ 程度の因子で古典論よりも大きくなる。これらを代入し、さらに電気伝導度 $\sigma=\frac{ne\tau}{m}$ を用いて緩和時間を消去すれば、雑な議論ながら $\frac{\kappa}{\sigma T}=\frac{\pi^2}{3}\left(\frac{k_B}{e}\right)^2$ なるWiedemann-Franz則が得られる。
* 熱起電力
    * Drudeの熱起電力の過大評価もFD統計を用いれば室温でDrudeの推定よりも2桁程度小さくなる。
* 他の性質
    * 分布関数に依存しない物理量は変化しない。