---
title: "ラプラス変換表と楽な思い出し方"
---

# ラプラス変換表

| $f(t)$ | $F(s)$ |
|:---:|:---:|
| $e^{at}$ | $\frac{1}{s-a}$ |
| $t^n$ | $\frac{n!}{s^{n+1}}$ |
| $\cosh at$ | $\frac{s}{s^2 - a^2}$ |
| $\sinh at$ | $\frac{a}{s^2 - a^2}$ |
| $\cos at$ | $\frac{s}{s^2 + a^2}$ |
| $\sin at$ | $\frac{a}{s^2 + a^2}$ |
| $t^n e^{at}$ | $\frac{n!}{(s-a)^{n+1}}$ |
| $t^n \cosh at$ | $\frac{n!}{2}\left(\frac{(s+a)^{n+1} + (s-a)^{n+1}}{(s^2 - a^2)^{n+1}}\right)$ |
| $t^n \sinh at$ | $\frac{n!}{2}\left(\frac{(s+a)^{n+1} - (s-a)^{n+1}}{(s^2 - a^2)^{n+1}}\right)$ |
| $t^n \cos at$ | $\frac{n!}{2}\left(\frac{(s+ia)^{n+1} + (s-ia)^{n+1}}{(s^2 + a^2)^{n+1}}\right)$ |
| $t^n \sin at$ | $\frac{n!}{2i}\left(\frac{(s+ia)^{n+1} - (s-ia)^{n+1}}{(s^2 + a^2)^{n+1}}\right)$ |
| $e^{at} \cosh bt$ | $\frac{s - a}{(s - a)^2 - b^2}$ |
| $e^{at} \sinh bt$ | $\frac{b}{(s - a)^2 - b^2}$ |
| $e^{at} \cos bt$ | $\frac{s - a}{(s - a)^2 + b^2}$ |
| $e^{at} \sin bt$ | $\frac{b}{(s - a)^2 + b^2}$ |


# 思い出し方

重要な試験などでラプラス変換表を全部忘れたときに全部思い出すためのメモです。私なりにどれだけ楽に思い出せるかを考えてみました。

ラプラス変換とは、$t \geq 0$ において、$f(t)$ を $s$ に関する関数 $F(s)$ に変換する操作

$$
F(s) = \int_0^\infty f(t) e^{-st} dt
$$

を指します。代表的なラプラス変換の例をまとめた**ラプラス変換表**は便利ですが、すべて覚えるのは大変です。そこで、ラプラス変換表をすべて忘れたときにどれだけ楽に思い出せるかを考えてみます。とりあえずよく見るラプラス変換表を掲載しておきます[^note]：

| $f(t)$ | $F(s)$ |
|:---:|:---:|
| $e^{at}$ | $\frac{1}{s-a}$ |
| $t^n$ | $\frac{n!}{s^{n+1}}$ |
| $\cosh at$ | $\frac{s}{s^2 - a^2}$ |
| $\sinh at$ | $\frac{a}{s^2 - a^2}$ |
| $\cos at$ | $\frac{s}{s^2 + a^2}$ |
| $\sin at$ | $\frac{a}{s^2 + a^2}$ |
| $t^n e^{at}$ | $\frac{n!}{(s-a)^{n+1}}$ |
| $t^n \cosh at$ | $\frac{n!}{2}\left(\frac{(s+a)^{n+1} + (s-a)^{n+1}}{(s^2 - a^2)^{n+1}}\right)$ |
| $t^n \sinh at$ | $\frac{n!}{2}\left(\frac{(s+a)^{n+1} - (s-a)^{n+1}}{(s^2 - a^2)^{n+1}}\right)$ |
| $t^n \cos at$ | $\frac{n!}{2}\left(\frac{(s+ia)^{n+1} + (s-ia)^{n+1}}{(s^2 + a^2)^{n+1}}\right)$ |
| $t^n \sin at$ | $\frac{n!}{2i}\left(\frac{(s+ia)^{n+1} - (s-ia)^{n+1}}{(s^2 + a^2)^{n+1}}\right)$ |
| $e^{at} \cosh bt$ | $\frac{s - a}{(s - a)^2 - b^2}$ |
| $e^{at} \sinh bt$ | $\frac{b}{(s - a)^2 - b^2}$ |
| $e^{at} \cos bt$ | $\frac{s - a}{(s - a)^2 + b^2}$ |
| $e^{at} \sin bt$ | $\frac{b}{(s - a)^2 + b^2}$ |

以下では、この変換表をすべて忘れたときの私なりの思い出し方を紹介します。この流れでラプラス変換表を思い出すのが私個人としては最も簡単に思われます。大まかな流れとしては、まず指数関数と冪乗のラプラス変換を思い出し、そこから色々な関数のラプラス変換表を構成していくというものです。

[^note]:例えば冪乗・指数関数のラプラス変換はそれぞれ $n=-1,-2,-3,\dots,\quad\mathrm{Re}(s)<a$ に対して定義できない、それにより他の関数も...など注意がありますが、今回はそれらはあとから思い出すことにして、細かい話は気にしないことにしました。


## Step 1

### 指数関数のラプラス変換

これはとても簡単なので説明する必要もないです。

$$
\begin{aligned}
\mathcal{L}[e^{at}](s) &= \int_0^\infty e^{at} e^{-st} dt \\
&= \int_0^\infty e^{-(s-a)t} dt \\
&= \left[ \frac{e^{-(s-a)t}}{-(s-a)} \right]_0^\infty \\
&= \frac{1}{s-a}
\end{aligned}
$$



### 冪乗のラプラス変換

冪乗のラプラス変換を思い出します。これはガンマ関数の定義から自明です。ガンマ関数は

$$
\Gamma(t) = \int_0^\infty x^{t-1} e^{-x} dx
$$

で定義される関数です。ガンマ関数は、$t$ が整数のときには階乗と1だけずれた関数に一致することが知られています：

$$
\Gamma(n) = (n-1)!
$$

ガンマ関数の定義より、冪乗のラプラス変換が導けます。

$$
\begin{aligned}
\mathcal{L}[t^n](s) &= \int_0^\infty t^n e^{-st} dt \\
&= \int_0^\infty \frac{1}{s} \left( \frac{t}{s} \right)^n e^{-st} dt \\
&= \frac{1}{s} \int_0^\infty x^n e^{-x} dx \\
&= \frac{n!}{s^{n+1}}
\end{aligned}
$$

実はこの式を思い出すのが一番大変で、あとは楽です。

## Step 2

指数関数、冪乗の和で書ける関数のラプラス変換表を構成します。
ラプラス変換を行う演算子 $\mathcal{L}$ は線形演算子であることを使います。

### 双曲線関数のラプラス変換

双曲線関数は指数関数の和で表せるので、指数関数のラプラス変換を使ってラプラス変換表を構成できます。

$$
\begin{aligned}
\mathcal{L}[\cosh at](s) &= \frac{1}{2} \mathcal{L}[e^{at} + e^{-at}](s) \\
&= \frac{1}{2} \left( \frac{1}{s-a} + \frac{1}{s+a} \right) \\
&= \frac{s}{s^2 - a^2}\\
\mathcal{L}[\sinh at](s) &= \frac{1}{2} \mathcal{L}[e^{at} - e^{-at}](s) \\
&= \frac{1}{2} \left( \frac{1}{s-a} - \frac{1}{s+a} \right) \\
&= \frac{a}{s^2 - a^2}
\end{aligned}
$$

### 三角関数のラプラス変換

複素指数関数に拡張することで、三角関数のラプラス変換を構成できます。

$$
\begin{aligned}
\mathcal{L}[\cos at](s) &= \frac{1}{2} \mathcal{L}[e^{iat} + e^{-iat}](s) \\
&= \frac{1}{2} \left( \frac{1}{s-ia} + \frac{1}{s+ia} \right) \\
&= \frac{s}{s^2 + a^2}\\
\mathcal{L}[\sin at](s) &= \frac{1}{2i} \mathcal{L}[e^{iat} - e^{-iat}](s) \\
&= \frac{1}{2i} \left( \frac{1}{s-ia} - \frac{1}{s+ia} \right) \\
&= \frac{a}{s^2 + a^2}
\end{aligned}
$$

どちらも結果が($s\in\mathbb{R}$ としたとき)実数になること、および元の関数と偶奇が入れ替わることを覚えておくと良いと思います。

## Step 3

ここでは、指数関数、冪乗の和と積で書ける関数のラプラス変換表を構成します。
重要なテクニックは積分範囲をずらすことで知っているラプラス変換表を使えるようにすることです。

### 指数関数と冪乗の積のラプラス変換

$$
\begin{aligned}
\mathcal{L}[t^n e^{at}](s) &= \mathcal{L}[t^n](s-a) \\
&= \frac{n!}{(s-a)^{n+1}}
\end{aligned}
$$

### 双曲線関数と冪乗の積のラプラス変換

$$
\begin{aligned}
\mathcal{L}[t^n \cosh at](s) &= \frac{1}{2}\left(\mathcal{L}
[t^n e^{at}](s) + \mathcal{L}[t^n e^{-at}](s)\right) \\
&= \frac{1}{2}\left(\frac{n!}{(s-a)^{n+1}} + \frac{n!}{(s+a)^{n+1}}\right) \\
&= \frac{n!}{2}\left(\frac{(s+a)^{n+1} + (s-a)^{n+1}}{(s^2 - a^2)^{n+1}}\right) \\
\mathcal{L}[t^n \sinh at](s) &= \frac{1}{2}\left(\mathcal{L}
[t^n e^{at}](s) - \mathcal{L}[t^n e^{-at}](s)\right) \\
&= \frac{1}{2}\left(\frac{n!}{(s-a)^{n+1}} - \frac{n!}{(s+a)^{n+1}}\right) \\
&= \frac{n!}{2}\left(\frac{(s+a)^{n+1} - (s-a)^{n+1}}{(s^2 - a^2)^{n+1}}\right)
\end{aligned}
$$



### 三角関数と冪乗の積のラプラス変換

$$
\begin{aligned}
\mathcal{L}[t^n \cos at](s) &= \frac{1}{2}\left(\mathcal{L}
[t^n e^{iat}](s) + \mathcal{L}[t^n e^{-iat}](s)\right) \\
&= \frac{1}{2}\left(\frac{n!}{(s-ia)^{n+1}} + \frac{n!}{(s+ia)^{n+1}}\right) \\
&= \frac{n!}{2}\left(\frac{(s+ia)^{n+1} + (s-ia)^{n+1}}{(s^2 + a^2)^{n+1}}\right) \\
\mathcal{L}[t^n \sin at](s) &= \frac{1}{2i}\left(\mathcal{L}
[t^n e^{iat}](s) - \mathcal{L}[t^n e^{-iat}](s)\right) \\
&= \frac{1}{2i}\left(\frac{n!}{(s-ia)^{n+1}} - \frac{n!}{(s+ia)^{n+1}}\right) \\
&= \frac{n!}{2i}\left(\frac{(s+ia)^{n+1} - (s-ia)^{n+1}}{(s^2 + a^2)^{n+1}}\right)
\end{aligned}
$$

### 指数関数と双曲線関数の積のラプラス変換

$$
\begin{aligned}
\mathcal{L}[e^{at} \cosh bt](s) &= \frac{1}{2}\left(\mathcal{L}
[e^{at + bt}](s) + \mathcal{L}[e^{at - bt}](s)\right) \\
&= \frac{1}{2}\left(\frac{1}{s - (a + b)} + \frac{1}{s - (a - b)}\right) \\
&= \frac{s - a}{(s - a)^2 - b^2} \\
\mathcal{L}[e^{at} \sinh bt](s) &= \frac{1}{2}\left(\mathcal{L}
[e^{at + bt}](s) - \mathcal{L}[e^{at - bt}](s)\right) \\
&= \frac{1}{2}\left(\frac{1}{s - (a + b)} - \frac{1}{s - (a - b)}\right) \\
&= \frac{b}{(s - a)^2 - b^2}
\end{aligned}
$$


### 指数関数と三角関数の積のラプラス変換

$$
\begin{aligned}
\mathcal{L}[e^{at} \cos bt](s) &= \frac{1}{2}\left(\mathcal{L}
[e^{at + ibt}](s) + \mathcal{L}[e^{at - ibt}](s)\right) \\
&= \frac{1}{2}\left(\frac{1}{s - (a + ib)} + \frac{1}{s - (a - ib)}\right) \\
&= \frac{s - a}{(s - a)^2 + b^2} \\
\mathcal{L}[e^{at} \sin bt](s) &= \frac{1}{2i}\left(\mathcal{L}
[e^{at + ibt}](s) - \mathcal{L}[e^{at - ibt}](s)\right) \\
&= \frac{1}{2i}\left(\frac{1}{s - (a + ib)} - \frac{1}{s - (a - ib)}\right) \\
&= \frac{b}{(s - a)^2 + b^2}
\end{aligned}
$$

# コメント

実質的に冪乗のラプラス変換を覚えておくだけで標準的なラプラス変換表は再現できます[^aori]。

[^aori]:むしろ、世の人々の「ラプラス変換表を忘れてしまった」という発言の真意は単に最近ラプラス変換を使っていなくて結果が合っているか自信がないだけなのではないかと思います。

もうわかってきた思いますが、少しイレギュラーなラプラス変換でも同じように対処できます。例えばこんな感じのものです。

$$
\begin{aligned}
\mathcal{L}[\cosh at \cosh bt](s) &= \frac{1}{2}\left(\mathcal{L}[e^{at}\cosh bt](s) + \mathcal{L}[e^{-at}\cosh bt](s)\right) \\
&= \frac{1}{2}\left(\frac{s - a}{(s - a)^2 - b^2} + \frac{s + a}{(s + a)^2 - b^2}\right) \\
&= \frac{s^2 + a^2 - b^2}{(s^2 - a^2)^2 - 4a^2b^2} \\
\end{aligned}
$$

つまり、**覚えるべきは冪乗のラプラス変換 $=$ ガンマ関数だけ**で、あとは指数関数のラプラス変換を使って色々な関数のラプラス変換を構成できます。ラプラス変換表を覚える必要はありません。

この方法では特殊関数($\sin x, \cos x, \sinh x, \cosh x$ など)の引数部分($x$)が $x=at$ のようになっている場合のラプラス変換はかなり簡単に構成できますが、引数部分が $x=at+b$ のようになっている場合や、引数部分が $x=at^2$ のようになっている場合は他の方法を考えるほうが早く計算できる場合があることに注意してください。